name: Tests
on:
  push:
    branches:
      - $default-branch
  pull_request:
jobs:
  test:
    name: Test sparksteps on Python ${{ matrix.python_version }}
    strategy:
      matrix:
        python_version: [3.6, 3.7, 3.8]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - name: Run tests on Python ${{ matrix.python_version }}
        run: make test
